# Generated by Django 3.2.9 on 2022-02-09 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authors', models.CharField(max_length=80)),
                ('year', models.CharField(max_length=4)),
                ('edition', models.CharField(max_length=10)),
                ('volume', models.CharField(max_length=10)),
                ('no_of_pages', models.CharField(max_length=20)),
                ('publisher', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=15)),
                ('title', models.CharField(max_length=30)),
                ('journal', models.CharField(max_length=200)),
                ('bookTitle', models.CharField(max_length=200)),
                ('referenceType', models.CharField(max_length=200)),
            ],
        ),
    ]
