# Generated by Django 3.2.9 on 2022-03-03 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0002_auto_20220303_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxonomicunit',
            name='rank_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='front.taxonunittype'),
        ),
        migrations.AlterField(
            model_name='taxonomicunit',
            name='taxon_author_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='front.taxonauthorlkp'),
        ),
    ]
