# Generated by Django 3.2.9 on 2022-03-14 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0003_auto_20220303_1457'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expertsgeographicdiv',
            old_name='expert_id',
            new_name='expert',
        ),
        migrations.RenameField(
            model_name='expertsgeographicdiv',
            old_name='geographic_id',
            new_name='geographic',
        ),
        migrations.RenameField(
            model_name='geographicdiv',
            old_name='taxon_id',
            new_name='taxon',
        ),
        migrations.RenameField(
            model_name='hierarchy',
            old_name='taxon_id',
            new_name='taxon',
        ),
        migrations.RenameField(
            model_name='referencelink',
            old_name='documentation_id',
            new_name='documentation',
        ),
        migrations.RenameField(
            model_name='referencelink',
            old_name='taxon_id',
            new_name='taxon',
        ),
        migrations.RenameField(
            model_name='taxonomicunit',
            old_name='rank_id',
            new_name='rank',
        ),
        migrations.RenameField(
            model_name='taxonomicunit',
            old_name='taxon_author_id',
            new_name='taxon_author',
        ),
        migrations.RenameField(
            model_name='tucommentlink',
            old_name='comment_id',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='tucommentlink',
            old_name='taxon_id',
            new_name='taxon',
        ),
    ]
