# Generated by Django 3.2.9 on 2022-04-07 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0003_auto_20220407_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxonomicunit',
            name='expert',
            field=models.ManyToManyField(blank=True, null=True, to='front.Expert'),
        ),
    ]
