# Generated by Django 3.2.9 on 2022-03-14 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0004_auto_20220314_1041'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='referencelink',
            unique_together={('taxon_id', 'doc_id_prefix', 'documentation_id')},
        ),
    ]
