# Generated by Django 3.2.9 on 2022-04-30 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0004_taxonomicunit_expert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expert',
            name='exp_comment',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
