# Generated by Django 3.2.9 on 2022-03-24 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0004_auto_20220324_1014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taxonomicunit',
            name='reference',
        ),
        migrations.AddField(
            model_name='taxonomicunit',
            name='reference',
            field=models.ManyToManyField(blank=True, null=True, to='front.Reference'),
        ),
    ]
