# Generated by Django 3.2.9 on 2022-03-24 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0005_auto_20220324_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxonomicunit',
            name='reference',
            field=models.ManyToManyField(to='front.Reference'),
        ),
    ]
