# Generated by Django 3.2.9 on 2022-03-14 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0005_alter_referencelink_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expertsgeographicdiv',
            name='geographic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='front.geographicdiv'),
        ),
        migrations.AlterUniqueTogether(
            name='referencelink',
            unique_together={('taxon', 'doc_id_prefix', 'documentation')},
        ),
    ]
