# Generated by Django 3.2.9 on 2022-06-20 11:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0006_add_basemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 20, 11, 24, 28, 395742, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='comment',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 20, 11, 24, 28, 395768, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='expert',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 20, 11, 24, 28, 395742, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='expert',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 20, 11, 24, 28, 395768, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='expertsgeographicdiv',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 20, 11, 24, 28, 395742, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='expertsgeographicdiv',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 20, 11, 24, 28, 395768, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='geographicdiv',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 20, 11, 24, 28, 395742, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='geographicdiv',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 20, 11, 24, 28, 395768, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='hierarchy',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 20, 11, 24, 28, 395742, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='hierarchy',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 20, 11, 24, 28, 395768, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='historicalreference',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 20, 11, 24, 28, 395742, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='historicalreference',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 20, 11, 24, 28, 395768, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='historicaltaxonauthorlkp',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 20, 11, 24, 28, 395742, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='historicaltaxonauthorlkp',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 20, 11, 24, 28, 395768, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='kingdom',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 20, 11, 24, 28, 395742, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='kingdom',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 20, 11, 24, 28, 395768, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='publication',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 20, 11, 24, 28, 395742, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='publication',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 20, 11, 24, 28, 395768, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='reference',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 20, 11, 24, 28, 395742, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='reference',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 20, 11, 24, 28, 395768, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='referencelink',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 20, 11, 24, 28, 395742, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='referencelink',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 20, 11, 24, 28, 395768, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='synonymlink',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 20, 11, 24, 28, 395742, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='synonymlink',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 20, 11, 24, 28, 395768, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='taxonauthorlkp',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 20, 11, 24, 28, 395742, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='taxonauthorlkp',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 20, 11, 24, 28, 395768, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='taxonomicunit',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 20, 11, 24, 28, 395742, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='taxonomicunit',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 20, 11, 24, 28, 395768, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='taxonunittype',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 20, 11, 24, 28, 395742, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='taxonunittype',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 20, 11, 24, 28, 395768, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='tucommentlink',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 20, 11, 24, 28, 395742, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='tucommentlink',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 20, 11, 24, 28, 395768, tzinfo=utc)),
        ),
    ]
