# Generated by Django 3.2.9 on 2022-03-24 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0007_auto_20220324_1047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taxonomicunit',
            name='reference',
        ),
        migrations.AddField(
            model_name='taxonomicunit',
            name='references',
            field=models.ManyToManyField(to='front.Reference'),
        ),
    ]
