# Generated by Django 3.2.9 on 2022-03-29 08:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('front', '0008_auto_20220324_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='geographicdiv',
            name='geo_taxon',
            field=models.ManyToManyField(to='front.TaxonomicUnit'),
        ),
        migrations.AddField(
            model_name='taxonauthorlkp',
            name='geographic_div',
            field=models.ManyToManyField(to='front.GeographicDiv'),
        ),
        migrations.AlterField(
            model_name='expert',
            name='update_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='referencelink',
            name='update_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='synonymlink',
            name='update_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='taxonauthorlkp',
            name='taxon_author_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='geographicdiv',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='HistoricalTaxonAuthorLkp',
            fields=[
                ('taxon_author_id', models.IntegerField(blank=True, db_index=True)),
                ('taxon_author', models.CharField(blank=True, max_length=100, null=True)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
                ('short_author', models.CharField(blank=True, max_length=100, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('kingdom', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='front.kingdom')),
            ],
            options={
                'verbose_name': 'historical taxon author lkp',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.RemoveField(
            model_name='geographicdiv',
            name='experts',
        ),
        migrations.RemoveField(
            model_name='geographicdiv',
            name='taxon',
        ),
    ]
