# Generated by Django 3.2.9 on 2022-06-21 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0009_add_simplehistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comment_time_stamp',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='update_date',
        ),
        migrations.RemoveField(
            model_name='expert',
            name='update_date',
        ),
        migrations.RemoveField(
            model_name='geographicdiv',
            name='update_date',
        ),
        migrations.RemoveField(
            model_name='historicalcomment',
            name='comment_time_stamp',
        ),
        migrations.RemoveField(
            model_name='historicalcomment',
            name='update_date',
        ),
        migrations.RemoveField(
            model_name='historicalexpert',
            name='update_date',
        ),
        migrations.RemoveField(
            model_name='historicalgeographicdiv',
            name='update_date',
        ),
        migrations.RemoveField(
            model_name='historicalkingdom',
            name='update_date',
        ),
        migrations.RemoveField(
            model_name='historicalpublication',
            name='update_date',
        ),
        migrations.RemoveField(
            model_name='historicalreferencelink',
            name='update_date',
        ),
        migrations.RemoveField(
            model_name='historicalsynonymlink',
            name='update_date',
        ),
        migrations.RemoveField(
            model_name='historicaltaxonauthorlkp',
            name='update_date',
        ),
        migrations.RemoveField(
            model_name='historicaltaxonomicunit',
            name='initial_time_stamp',
        ),
        migrations.RemoveField(
            model_name='historicaltaxonomicunit',
            name='update_date',
        ),
        migrations.RemoveField(
            model_name='historicaltaxonunittype',
            name='update_date',
        ),
        migrations.RemoveField(
            model_name='historicaltucommentlink',
            name='update_date',
        ),
        migrations.RemoveField(
            model_name='kingdom',
            name='update_date',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='update_date',
        ),
        migrations.RemoveField(
            model_name='referencelink',
            name='update_date',
        ),
        migrations.RemoveField(
            model_name='synonymlink',
            name='update_date',
        ),
        migrations.RemoveField(
            model_name='taxonauthorlkp',
            name='update_date',
        ),
        migrations.RemoveField(
            model_name='taxonomicunit',
            name='initial_time_stamp',
        ),
        migrations.RemoveField(
            model_name='taxonomicunit',
            name='update_date',
        ),
        migrations.RemoveField(
            model_name='taxonunittype',
            name='update_date',
        ),
        migrations.RemoveField(
            model_name='tucommentlink',
            name='update_date',
        ),
    ]
