# Generated by Django 3.2.9 on 2022-07-08 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0010_auto_20220621_1405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taxonomicunit',
            name='references',
        ),
        migrations.AddField(
            model_name='historicaltaxonomicunit',
            name='reference',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='front.reference'),
        ),
        migrations.AddField(
            model_name='taxonomicunit',
            name='reference',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='front.reference'),
        ),
        migrations.AlterField(
            model_name='taxonomicunit',
            name='expert',
            field=models.ManyToManyField(blank=True, to='front.Expert'),
        ),
        migrations.AlterField(
            model_name='taxonomicunit',
            name='geographic_div',
            field=models.ManyToManyField(blank=True, to='front.GeographicDiv'),
        ),
    ]
