# Generated by Django 3.2.9 on 2022-07-08 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0011_reference_as_foreignkey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalexpertsgeographicdiv',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='historicalexpertsgeographicdiv',
            name='expert',
        ),
        migrations.RemoveField(
            model_name='historicalexpertsgeographicdiv',
            name='geographic',
        ),
        migrations.RemoveField(
            model_name='historicalexpertsgeographicdiv',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalexpertsgeographicdiv',
            name='modified_by',
        ),
        migrations.DeleteModel(
            name='ExpertsGeographicDiv',
        ),
        migrations.DeleteModel(
            name='HistoricalExpertsGeographicDiv',
        ),
    ]
