name: ci-staging

on:
  push:
    branches:
      - 'cypress_login'

jobs:
  test:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        working-directory: ./app
      - name: Run backend
        run: python manage.py runserver
        working-directory: ./app

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
            wait-on: http://localhost:8000
            config: baseUrl=http://localhost:8000
    