name: ci-main

on:
  push:
    branches:
      - 'main'

jobs:
  test:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        working-directory: ./app
      - name: Make migrations
        run: |
          python manage.py makemigrations
          python manage.py migrate
        working-directory: ./app
      - name: Run backend
        run: python manage.py runserver &
        working-directory: ./app
