name: ci-staging

on:
  push:
    branches:
      - 'staging'

jobs:
  test:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        working-directory: ./app
      - name: Run backend
        run: python manage.py testserver testdata/SampleData &
        working-directory: ./app

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
            wait-on: http://localhost:8000
            config: baseUrl=http://localhost:8000

  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./app
          push: true
          tags: palaeontologyhelsinki/taxonmanager_staging:latest